version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 7Ji34yE5LckM
      MYSQL_DATABASE: app 
    volumes:
      - ./ecommercedata.sql:/docker-entrypoint-initdb.d/ecommercedata.sql
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      - db

